#bin/bash/
echo "This is testing from git repository"
echo "This is testing from git repository"
echo "This is testing from git repository"
echo "This is testing from git repository"
echo "This is testing from git repository"
echo "This is testing from git repository"
echo "This is testing from git repository"
echo "This is testing from git repository"
echo "This is testing from git repository"
